product_core:
    resource: "@ProductCoreBundle/Controller/"
    type:     annotation
    prefix:   /

category_core:
    resource: "@CategoryCoreBundle/Controller/"
    type:     annotation
    prefix:   /




