admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

product_core:
    resource: "@ProductCoreBundle/Controller/"
    type:     annotation
    prefix:   /

category_core:
    resource: "@CategoryCoreBundle/Controller/"
    type:     annotation
    prefix:   /




