<?php

namespace Application\Sonata\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all users which are not vendor
     *
     * @param array $arrValues
     *
     * @return QueryBuilder
     */
    public function getAvailableForAddingUsersQueryBuilder($arrValues)
    {
        $qb = $this->getQueryBuilder();
        $qb
            ->select('u')
            ->where($qb->expr()->notIn('u.id', $arrValues))
        ;

        return $qb;
    }

    /**
     * Get all users which are not vendor
     *
     * @param array $arrValues
     *
     * @return \Doctrine\ORM\Query
     */
    public function getAvailableForAddingUsersQuery($arrValues)
    {
        return $this->getAvailableForAddingUsersQueryBuilder($arrValues)->getQuery();
    }

    /**
     * Get all users which are not vendor
     *
     * @param array $arrValues
     *
     * @return array
     */
    public function getAvailableForAddingUsers($arrValues)
    {
        return $this->getAvailableForAddingUsersQuery($arrValues)->getResult();
    }

    /**
     * @return QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager('ApplicationSonataUserBundle:User');
        $qb = $em->getRepository('ApplicationSonataUserBundle:User')
            ->createQueryBuilder('u');

        return $qb;
    }
}
